### ISSUE TITLE
docker-fullstack-app 실행 에러 문의

### ISSUE THREAD

**Issue by wann2** [jaewonhimnae/docker-codes#2]
강의를 들으면서 하나하나 따라하면서 실습을 해보고 있습니다.
나름대로 따라하면서 작업하는데 계속 에러가 발생해서 어쩔 수 없이
Git에서 다운받아 docker-fullstack-app 을 통째로 받아 실행해봐도 에러가 발생합니다.
http://localhost:3000 을 하면 아래처럼 Nginx 에러가 화면에 뜹니다.

502 Bad Gateway 
nginx/1.21.6

http://localhost:3000/api/hi 하면 backend는 정상응답합니다.

docker-compose up --build 하면 아래와 같은 메시지가 보이긴 합니다.

docker-fullstack-app-frontend-1  | Starting the development server...
docker-fullstack-app-frontend-1  | 
docker-fullstack-app-frontend-1  | /app/node_modules/react-scripts/scripts/start.js:19
docker-fullstack-app-frontend-1  |   throw err;
docker-fullstack-app-frontend-1  |   ^
docker-fullstack-app-frontend-1  | 
docker-fullstack-app-frontend-1  | Error: error:0308010C:digital envelope routines::unsupported
docker-fullstack-app-frontend-1  |     at new Hash (node:internal/crypto/hash:67:19)
docker-fullstack-app-frontend-1  |     at Object.createHash (node:crypto:135:10)
docker-fullstack-app-frontend-1  |     at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
docker-fullstack-app-frontend-1  |     at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
docker-fullstack-app-frontend-1  |     at /app/node_modules/webpack/lib/NormalModule.js:452:10
docker-fullstack-app-frontend-1  |     at /app/node_modules/webpack/lib/NormalModule.js:323:13
docker-fullstack-app-frontend-1  |     at /app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
docker-fullstack-app-frontend-1  |     at /app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
docker-fullstack-app-frontend-1  |     at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
docker-fullstack-app-frontend-1  |     at /app/node_modules/babel-loader/lib/index.js:59:103 {
docker-fullstack-app-frontend-1  |   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
docker-fullstack-app-frontend-1  |   library: 'digital envelope routines',
docker-fullstack-app-frontend-1  |   reason: 'unsupported',
docker-fullstack-app-frontend-1  |   code: 'ERR_OSSL_EVP_UNSUPPORTED'
docker-fullstack-app-frontend-1  | }

사용하는 노트북은 맥북프로(인텔)입니다.

**Comment by JaeHyeon-KAIST** [comment]
올리신지 좀 된 이슈이기는 한데, 그래도 의견 남겨봅니다.
저도 동일하게 500에러가 발생하는데, /api/values 즉 mysql 관련된 api만 500이라서 찾아봤습니다
https://github.com/mysqljs/mysql/issues/2390
mysql 버전이 변경됨에 따라 생긴 문제인것 같습니다

backend에서 mysql 패키지를 mysql2 패키지로 변경하면 잘 작동합니다.
